### ISSUE TITLE
Exception is thrown when invalid api_key is passed

### ISSUE THREAD

**Issue by nikiatanasow** [rentshare/rentshare-node#1]
### Description

If you pass invalid api_key to the place object and try to make a request an exception is thrown.

### Steps to Reproduce

- Set invalid access token to the place object (for example `test_private_key_invalid_value`).
- try to make any request.

### Expected Behavior

The promise should be rejected.

### Actual Behavior

Exception is thrown. The exception cannot be catched.

### Code snipped that reproduce the issue:

```
const place = require('place-api');
place.api_key = 'test_private_key_invalid_value';

try {
    var account = place.Account.get()
        .then(function(account) {
            console.log(account)
        }).catch(function(error) {
            console.log(error);
    });
} catch (error) {
    console.log(error);
}
```

### Output:

```
Unauthorized: api_sessions
    at Request._callback (/Users/atanasov/Desktop/work/place-test/node_modules/place-api/lib/APIResource.js:138:31)
    at Request.self.callback (/Users/atanasov/Desktop/work/place-test/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/atanasov/Desktop/work/place-test/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/atanasov/Desktop/work/place-test/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

**Comment by nedyalkov** [comment]
The error doesn't seem to be resolved for the last 2 years, but it changed a bit. The PlacePay server now returns HTML:
```
<div class="inset_box bevel_text" style="text-align:center;font-size:1.2em;">
    	<h2 class="jtk_window_header">Whoops, something didn't work!</h2>
    	<p class="light">
    		Please try again or refresh the page.<br/> If that doesn't work give
    		us a call at (800) 621-1423<br/>
    		or send us an <a href="mailto:contact@placepay.com">email</a> and we will gladly help you.
    	</p>
    	<p>
    		<img class="dropshadow rounded_corners" src="//s3.amazonaws.com/static.rentshare.com/common/style/graphics/whoops_error.gif" style="max-height:200px"/>
    	</p>
    </div>
```

Are there any plans for resolving this? It just needs to reject the promise with the error returned from the server, so it can be handled in the application... Otherwise, the promise is left unresolved forever.
